
/*
 *	This file was automatically generated by dbusxx-xml2cpp; DO NOT EDIT!
 */

#ifndef __dbusxx__MyDBusClass_proxy_hpp__PROXY_MARSHAL_H
#define __dbusxx__MyDBusClass_proxy_hpp__PROXY_MARSHAL_H

#include <dbus-c++/dbus.h>
#include <cassert>

namespace Morpho {
namespace MA5G {

class MyDBusClass_proxy
: public ::DBus::InterfaceProxy
{
public:

    MyDBusClass_proxy()
    : ::DBus::InterfaceProxy("Morpho.MA5G.MyDBusClass")
    {
    }

public:

    /* properties exported by this interface */
public:

    /* methods exported by this interface,
     * this functions will invoke the corresponding methods on the remote objects
     */
    int32_t Random()
    {
        ::DBus::CallMessage call;
        call.member("Random");
        ::DBus::Message ret = invoke_method (call);
        ::DBus::MessageIter ri = ret.reader();

        int32_t argout;
        ri >> argout;
        return argout;
    }


public:

    /* signal handlers for this interface
     */

private:

    /* unmarshalers (to unpack the DBus message before calling the actual signal handler)
     */
};

} } 
#endif //__dbusxx__MyDBusClass_proxy_hpp__PROXY_MARSHAL_H
