
/*
 *	This file was automatically generated by dbusxx-xml2cpp; DO NOT EDIT!
 */

#ifndef __dbusxx__MyDBusClass_adaptor_hpp__ADAPTOR_MARSHAL_H
#define __dbusxx__MyDBusClass_adaptor_hpp__ADAPTOR_MARSHAL_H

#include <dbus-c++/dbus.h>
#include <cassert>

namespace Morpho {
namespace MA5G {

class MyDBusClass_adaptor
: public ::DBus::InterfaceAdaptor
{
public:

    MyDBusClass_adaptor()
    : ::DBus::InterfaceAdaptor("Morpho.MA5G.MyDBusClass")
    {
        register_method(MyDBusClass_adaptor, Random, _Random_stub);
    }

    ::DBus::IntrospectedInterface *introspect() const 
    {
        static ::DBus::IntrospectedArgument Random_args[] = 
        {
            { "version", "i", false },
            { 0, 0, 0 }
        };
        static ::DBus::IntrospectedMethod MyDBusClass_adaptor_methods[] = 
        {
            { "Random", Random_args },
            { 0, 0 }
        };
        static ::DBus::IntrospectedMethod MyDBusClass_adaptor_signals[] = 
        {
            { 0, 0 }
        };
        static ::DBus::IntrospectedProperty MyDBusClass_adaptor_properties[] = 
        {
            { 0, 0, 0, 0 }
        };
        static ::DBus::IntrospectedInterface MyDBusClass_adaptor_interface = 
        {
            "Morpho.MA5G.MyDBusClass",
            MyDBusClass_adaptor_methods,
            MyDBusClass_adaptor_signals,
            MyDBusClass_adaptor_properties
        };
        return &MyDBusClass_adaptor_interface;
    }

public:

    /* properties exposed by this interface, use
     * property() and property(value) to get and set a particular property
     */

public:

    /* methods exported by this interface,
     * you will have to implement them in your ObjectAdaptor
     */
    virtual int32_t Random() = 0;

public:

    /* signal emitters for this interface
     */

private:

    /* unmarshalers (to unpack the DBus message before calling the actual interface method)
     */
    ::DBus::Message _Random_stub(const ::DBus::CallMessage &call)
    {
        ::DBus::MessageIter ri = call.reader();

        int32_t argout1 = Random();
        ::DBus::ReturnMessage reply(call);
        ::DBus::MessageIter wi = reply.writer();
        wi << argout1;
        return reply;
    }
};

} } 
#endif //__dbusxx__MyDBusClass_adaptor_hpp__ADAPTOR_MARSHAL_H
